[versions]
agp = "7.4.0-rc03"
detekt = "1.22.0"
dokka = "1.7.20"
jvm-target = "11"
kmmbridge = "0.3.4"
kotlin = "1.8.0"
ktfmt = "0.39"
mavenPublish = "0.23.1"
stately = "1.2.3"
spotless = "6.11.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
bestPracticesPlugin = { id = "com.autonomousapps.plugin-best-practices-plugin", version.ref = "gradle.bestPracticesPlugin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "gradle.dependencyAnalysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kmmbridge = { id = "co.touchlab.faktory.kmmbridge", version.ref = "kmmbridge" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-samWithReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
stately-collections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }
